### ISSUE TITLE
See Nothing

### ISSUE THREAD

**Issue by jugla** [zibous/lovelace-graph-chart-card#1]
Thanks for your new graph !
I try with a basic configuration 
`type: 'custom:chart-card'`
`height: 240`
`chart: line`
`entities:`
`  - entity: sensor.netatmo_netatmo_sceaux_anemometre_balcon_angle`
`    color: '#FECB2E'`

==> side effects : you must reload all the page to see your previous work (otherwise the page is blank)
==> once reload, the graph is not seenable at all

Thanks for your help

**Comment by zibous** [comment]
fixed with  0.0.4
